/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 12;
  /** RegularExpression Id. */
  int WORD = 13;
  /** RegularExpression Id. */
  int TYPE = 14;
  /** RegularExpression Id. */
  int BODY = 15;
  /** RegularExpression Id. */
  int DECLARATIONS = 16;
  /** RegularExpression Id. */
  int ID = 17;
  /** RegularExpression Id. */
  int INIT = 18;
  /** RegularExpression Id. */
  int OPERATOR = 19;
  /** RegularExpression Id. */
  int LEFT = 20;
  /** RegularExpression Id. */
  int RIGHT = 21;
  /** RegularExpression Id. */
  int VALUE = 22;
  /** RegularExpression Id. */
  int RAW = 23;
  /** RegularExpression Id. */
  int KIND = 24;
  /** RegularExpression Id. */
  int SOURCE_TYPE = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"\\\"\"",
    "\"\\n\"",
    "\":\"",
    "\",\"",
    "<INTEGER>",
    "<WORD>",
    "\"type\"",
    "\"body\"",
    "\"declarations\"",
    "\"id\"",
    "\"init\"",
    "\"operator\"",
    "\"left\"",
    "\"right\"",
    "\"value\"",
    "\"raw\"",
    "\"kind\"",
    "\"sourceType\"",
  };

}
