/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTBODY = 1;
  public int JJTTYPE = 2;
  public int JJTTYPE_NAME = 3;


  public String[] jjtNodeName = {
    "Expression",
    "body",
    "type",
    "type_name",
  };
}
/* JavaCC - OriginalChecksum=aa69abf75337288239fdbebd18db65ea (do not edit this line) */
